###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
services:
    php:
        build: docker/php
        volumes:
            - '.:/var/www/app'
            - './docker/php/conf.d:/usr/local/etc/php/conf.d'
        expose:
            - 80
        ports:
            - 80:80
        restart: unless-stopped